// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample;

namespace SampleApi.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20181010203855_initialDemo")]
    partial class initialDemo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<string>("LastName");

                    b.Property<string>("Profile");

                    b.Property<string>("TagLine");

                    b.Property<string>("Title")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new { Id = 1, Email = "foo@foo.com", FirstName = "Foo", LastName = "Bar", Profile = "Foo Bar Bar Foo", TagLine = "FooBar", Title = "Mr" },
                        new { Id = 2, Email = "foo2@foo2.com", FirstName = "Foo2", LastName = "Bar2", Profile = "Foo Bar Bar Foo2", TagLine = "FooBar2", Title = "Mr" },
                        new { Id = 3, Email = "foo3@foo3.com", FirstName = "Foo3", LastName = "Bar3", Profile = "Foo Bar Bar Foo3", TagLine = "FooBar3", Title = "Mr" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
